repos:
  - repo: local
    hooks:
      - id: gha-sha-convert
        name: GitHub Actions SHA Converter
        description: Convert GitHub Actions to use SHA-pinned versions
        entry: gha-sha-convert
        language: python
        files: ^\.github/(workflows|actions)/.*\.(yml|yaml)$
        pass_filenames: true
