name: Stale PR Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write

jobs:
  stale-pr-cleanup:
    uses: Alfresco/alfresco-build-tools/.github/workflows/stale-pr-cleanup.yml@d92786682ac60f54c36b3130fa6d86b599c503d5 # v19.3.0
